/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AllUserData {
  'tasks' : Array<Task>,
  'projects' : Array<Project>,
  'productLibrary' : Array<ProductLibrary>,
  'userProfile' : UserProfile,
  'moodboards' : Array<Moodboard>,
  'shoppingLists' : Array<ShoppingList>,
}
export interface Document {
  'id' : bigint,
  'file' : string,
  'name' : string,
  'fileSize' : bigint,
  'projectId' : bigint,
  'docType' : string,
  'format' : string,
}
export interface Material {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'image' : string,
  'price' : bigint,
  'format' : string,
}
export interface Moodboard {
  'id' : bigint,
  'name' : string,
  'totalCost' : bigint,
  'description' : string,
  'projectId' : bigint,
  'roomId' : bigint,
  'products' : Array<string>,
  'images' : Array<string>,
}
export interface Product {
  'id' : bigint,
  'status' : string,
  'link' : string,
  'name' : string,
  'shop' : string,
  'availability' : string,
  'projectId' : bigint,
  'quantity' : bigint,
  'image' : string,
  'roomId' : bigint,
  'price' : bigint,
}
export interface ProductLibrary {
  'id' : bigint,
  'ownerId' : Principal,
  'name' : string,
  'shop' : string,
  'type' : string,
  'description' : string,
  'image' : string,
  'price' : bigint,
}
export interface Project {
  'id' : bigint,
  'status' : string,
  'clientId' : bigint,
  'ownerId' : Principal,
  'name' : string,
  'sharedWithClients' : Array<Principal>,
  'budget' : bigint,
  'rooms' : Array<Room>,
  'timeline' : string,
}
export type Role = { 'client' : null } |
  { 'manager' : null } |
  { 'admin' : null } |
  { 'designer' : null };
export interface Room {
  'id' : bigint,
  'area' : bigint,
  'name' : string,
  'notes' : string,
  'category' : string,
  'products' : Array<Product>,
  'budget' : bigint,
}
export interface ShoppingList {
  'id' : bigint,
  'status' : string,
  'total' : bigint,
  'ownerId' : Principal,
  'name' : string,
  'shop' : string,
  'discount' : bigint,
  'products' : Array<Product>,
}
export interface Task {
  'id' : bigint,
  'status' : string,
  'assigned' : string,
  'title' : string,
  'ownerId' : Principal,
  'type' : string,
  'description' : string,
  'deadline' : string,
  'projectId' : bigint,
  'roomId' : bigint,
}
export interface UserProfile {
  'id' : bigint,
  'name' : string,
  'role' : Role,
  'email' : string,
  'company' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMaterial' : ActorMethod<
    [bigint, string, string, string, string, bigint],
    undefined
  >,
  'addProject' : ActorMethod<
    [bigint, string, bigint, string, bigint, string, Array<Room>],
    undefined
  >,
  'addRoom' : ActorMethod<
    [bigint, bigint, string, bigint, string, string, bigint, Array<Product>],
    undefined
  >,
  'addShoppingList' : ActorMethod<
    [bigint, string, bigint, bigint, string, Array<Product>, string],
    undefined
  >,
  'addTask' : ActorMethod<
    [bigint, string, string, string, string, bigint, bigint, string, string],
    undefined
  >,
  'addToProductLibrary' : ActorMethod<
    [bigint, string, string, bigint, string, string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllTasks' : ActorMethod<[bigint], Array<Task>>,
  'getAllUserData' : ActorMethod<[], AllUserData>,
  'getAllUsersData' : ActorMethod<[], Array<AllUserData>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDocuments' : ActorMethod<[bigint], Array<Document>>,
  'getMaterialsByIds' : ActorMethod<[Array<bigint>], Array<Material>>,
  'getMyProjects' : ActorMethod<[], Array<Project>>,
  'getProductLibrary' : ActorMethod<[], Array<ProductLibrary>>,
  'getProject' : ActorMethod<[bigint], [] | [Project]>,
  'getShoppingLists' : ActorMethod<[], Array<ShoppingList>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'shareProjectWithClient' : ActorMethod<[bigint, Principal], undefined>,
  'updateDocument' : ActorMethod<
    [bigint, string, string, bigint, string, bigint, string],
    undefined
  >,
  'updateUser' : ActorMethod<
    [bigint, string, string, string, string, Role],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];