/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'link' : IDL.Text,
  'name' : IDL.Text,
  'shop' : IDL.Text,
  'availability' : IDL.Text,
  'projectId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'image' : IDL.Text,
  'roomId' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Room = IDL.Record({
  'id' : IDL.Nat,
  'area' : IDL.Nat,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'category' : IDL.Text,
  'products' : IDL.Vec(Product),
  'budget' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'assigned' : IDL.Text,
  'title' : IDL.Text,
  'ownerId' : IDL.Principal,
  'type' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : IDL.Text,
  'projectId' : IDL.Nat,
  'roomId' : IDL.Nat,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'clientId' : IDL.Nat,
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'sharedWithClients' : IDL.Vec(IDL.Principal),
  'budget' : IDL.Nat,
  'rooms' : IDL.Vec(Room),
  'timeline' : IDL.Text,
});
export const ProductLibrary = IDL.Record({
  'id' : IDL.Nat,
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'shop' : IDL.Text,
  'type' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Text,
  'price' : IDL.Nat,
});
export const Role = IDL.Variant({
  'client' : IDL.Null,
  'manager' : IDL.Null,
  'admin' : IDL.Null,
  'designer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : Role,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'phone' : IDL.Text,
});
export const Moodboard = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'totalCost' : IDL.Nat,
  'description' : IDL.Text,
  'projectId' : IDL.Nat,
  'roomId' : IDL.Nat,
  'products' : IDL.Vec(IDL.Text),
  'images' : IDL.Vec(IDL.Text),
});
export const ShoppingList = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'total' : IDL.Nat,
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'shop' : IDL.Text,
  'discount' : IDL.Nat,
  'products' : IDL.Vec(Product),
});
export const AllUserData = IDL.Record({
  'tasks' : IDL.Vec(Task),
  'projects' : IDL.Vec(Project),
  'productLibrary' : IDL.Vec(ProductLibrary),
  'userProfile' : UserProfile,
  'moodboards' : IDL.Vec(Moodboard),
  'shoppingLists' : IDL.Vec(ShoppingList),
});
export const Document = IDL.Record({
  'id' : IDL.Nat,
  'file' : IDL.Text,
  'name' : IDL.Text,
  'fileSize' : IDL.Nat,
  'projectId' : IDL.Nat,
  'docType' : IDL.Text,
  'format' : IDL.Text,
});
export const Material = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Text,
  'price' : IDL.Nat,
  'format' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMaterial' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'addProject' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(Room)],
      [],
      [],
    ),
  'addRoom' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(Product),
      ],
      [],
      [],
    ),
  'addShoppingList' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(Product),
        IDL.Text,
      ],
      [],
      [],
    ),
  'addTask' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addToProductLibrary' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllTasks' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
  'getAllUserData' : IDL.Func([], [AllUserData], ['query']),
  'getAllUsersData' : IDL.Func([], [IDL.Vec(AllUserData)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocuments' : IDL.Func([IDL.Nat], [IDL.Vec(Document)], ['query']),
  'getMaterialsByIds' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Vec(Material)],
      ['query'],
    ),
  'getMyProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getProductLibrary' : IDL.Func([], [IDL.Vec(ProductLibrary)], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getShoppingLists' : IDL.Func([], [IDL.Vec(ShoppingList)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'shareProjectWithClient' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'updateDocument' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateUser' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, Role],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'link' : IDL.Text,
    'name' : IDL.Text,
    'shop' : IDL.Text,
    'availability' : IDL.Text,
    'projectId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'image' : IDL.Text,
    'roomId' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Room = IDL.Record({
    'id' : IDL.Nat,
    'area' : IDL.Nat,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'category' : IDL.Text,
    'products' : IDL.Vec(Product),
    'budget' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'assigned' : IDL.Text,
    'title' : IDL.Text,
    'ownerId' : IDL.Principal,
    'type' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : IDL.Text,
    'projectId' : IDL.Nat,
    'roomId' : IDL.Nat,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'clientId' : IDL.Nat,
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'sharedWithClients' : IDL.Vec(IDL.Principal),
    'budget' : IDL.Nat,
    'rooms' : IDL.Vec(Room),
    'timeline' : IDL.Text,
  });
  const ProductLibrary = IDL.Record({
    'id' : IDL.Nat,
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'shop' : IDL.Text,
    'type' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Role = IDL.Variant({
    'client' : IDL.Null,
    'manager' : IDL.Null,
    'admin' : IDL.Null,
    'designer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : Role,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Moodboard = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'totalCost' : IDL.Nat,
    'description' : IDL.Text,
    'projectId' : IDL.Nat,
    'roomId' : IDL.Nat,
    'products' : IDL.Vec(IDL.Text),
    'images' : IDL.Vec(IDL.Text),
  });
  const ShoppingList = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'total' : IDL.Nat,
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'shop' : IDL.Text,
    'discount' : IDL.Nat,
    'products' : IDL.Vec(Product),
  });
  const AllUserData = IDL.Record({
    'tasks' : IDL.Vec(Task),
    'projects' : IDL.Vec(Project),
    'productLibrary' : IDL.Vec(ProductLibrary),
    'userProfile' : UserProfile,
    'moodboards' : IDL.Vec(Moodboard),
    'shoppingLists' : IDL.Vec(ShoppingList),
  });
  const Document = IDL.Record({
    'id' : IDL.Nat,
    'file' : IDL.Text,
    'name' : IDL.Text,
    'fileSize' : IDL.Nat,
    'projectId' : IDL.Nat,
    'docType' : IDL.Text,
    'format' : IDL.Text,
  });
  const Material = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Text,
    'price' : IDL.Nat,
    'format' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMaterial' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'addProject' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(Room),
        ],
        [],
        [],
      ),
    'addRoom' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(Product),
        ],
        [],
        [],
      ),
    'addShoppingList' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(Product),
          IDL.Text,
        ],
        [],
        [],
      ),
    'addTask' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addToProductLibrary' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllTasks' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
    'getAllUserData' : IDL.Func([], [AllUserData], ['query']),
    'getAllUsersData' : IDL.Func([], [IDL.Vec(AllUserData)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocuments' : IDL.Func([IDL.Nat], [IDL.Vec(Document)], ['query']),
    'getMaterialsByIds' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(Material)],
        ['query'],
      ),
    'getMyProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getProductLibrary' : IDL.Func([], [IDL.Vec(ProductLibrary)], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getShoppingLists' : IDL.Func([], [IDL.Vec(ShoppingList)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'shareProjectWithClient' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'updateDocument' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateUser' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, Role],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };