/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProductLibrary {
    id: bigint;
    ownerId: Principal;
    name: string;
    shop: string;
    type: string;
    description: string;
    image: string;
    price: bigint;
}
export interface Product {
    id: bigint;
    status: string;
    link: string;
    name: string;
    shop: string;
    availability: string;
    projectId: bigint;
    quantity: bigint;
    image: string;
    roomId: bigint;
    price: bigint;
}
export interface Material {
    id: bigint;
    name: string;
    description: string;
    image: string;
    price: bigint;
    format: string;
}
export interface AllUserData {
    tasks: Array<Task>;
    projects: Array<Project>;
    productLibrary: Array<ProductLibrary>;
    userProfile: UserProfile;
    moodboards: Array<Moodboard>;
    shoppingLists: Array<ShoppingList>;
}
export interface Moodboard {
    id: bigint;
    name: string;
    totalCost: bigint;
    description: string;
    projectId: bigint;
    roomId: bigint;
    products: Array<string>;
    images: Array<string>;
}
export interface Document {
    id: bigint;
    file: string;
    name: string;
    fileSize: bigint;
    projectId: bigint;
    docType: string;
    format: string;
}
export interface Task {
    id: bigint;
    status: string;
    assigned: string;
    title: string;
    ownerId: Principal;
    type: string;
    description: string;
    deadline: string;
    projectId: bigint;
    roomId: bigint;
}
export interface ShoppingList {
    id: bigint;
    status: string;
    total: bigint;
    ownerId: Principal;
    name: string;
    shop: string;
    discount: bigint;
    products: Array<Product>;
}
export interface Room {
    id: bigint;
    area: bigint;
    name: string;
    notes: string;
    category: string;
    products: Array<Product>;
    budget: bigint;
}
export interface Project {
    id: bigint;
    status: string;
    clientId: bigint;
    ownerId: Principal;
    name: string;
    sharedWithClients: Array<Principal>;
    budget: bigint;
    rooms: Array<Room>;
    timeline: string;
}
export interface UserProfile {
    id: bigint;
    name: string;
    role: Role;
    email: string;
    company: string;
    phone: string;
}
export enum Role {
    client = "client",
    manager = "manager",
    admin = "admin",
    designer = "designer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMaterial(id: bigint, name: string, description: string, image: string, format: string, price: bigint): Promise<void>;
    addProject(id: bigint, name: string, clientId: bigint, timeline: string, budget: bigint, status: string, rooms: Array<Room>): Promise<void>;
    addRoom(projectId: bigint, id: bigint, name: string, area: bigint, notes: string, category: string, budget: bigint, products: Array<Product>): Promise<void>;
    addShoppingList(id: bigint, name: string, total: bigint, discount: bigint, shop: string, products: Array<Product>, status: string): Promise<void>;
    addTask(id: bigint, title: string, description: string, status: string, deadline: string, projectId: bigint, roomId: bigint, type: string, assigned: string): Promise<void>;
    addToProductLibrary(id: bigint, name: string, image: string, price: bigint, shop: string, description: string, type: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllTasks(projectId: bigint): Promise<Array<Task>>;
    getAllUserData(): Promise<AllUserData>;
    getAllUsersData(): Promise<Array<AllUserData>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDocuments(projectId: bigint): Promise<Array<Document>>;
    getMaterialsByIds(ids: Array<bigint>): Promise<Array<Material>>;
    getMyProjects(): Promise<Array<Project>>;
    getProductLibrary(): Promise<Array<ProductLibrary>>;
    getProject(id: bigint): Promise<Project | null>;
    getShoppingLists(): Promise<Array<ShoppingList>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    shareProjectWithClient(projectId: bigint, clientPrincipal: Principal): Promise<void>;
    updateDocument(id: bigint, name: string, format: string, fileSize: bigint, file: string, projectId: bigint, docType: string): Promise<void>;
    updateUser(id: bigint, name: string, email: string, phone: string, company: string, role: Role): Promise<void>;
}
import type { AllUserData as _AllUserData, Moodboard as _Moodboard, ProductLibrary as _ProductLibrary, Project as _Project, Role as _Role, ShoppingList as _ShoppingList, Task as _Task, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMaterial(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMaterial(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMaterial(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addProject(arg0: bigint, arg1: string, arg2: bigint, arg3: string, arg4: bigint, arg5: string, arg6: Array<Room>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addRoom(arg0: bigint, arg1: bigint, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: bigint, arg7: Array<Product>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRoom(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRoom(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addShoppingList(arg0: bigint, arg1: string, arg2: bigint, arg3: bigint, arg4: string, arg5: Array<Product>, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addShoppingList(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShoppingList(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addTask(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: bigint, arg7: string, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTask(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTask(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async addToProductLibrary(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToProductLibrary(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToProductLibrary(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllTasks(arg0: bigint): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks(arg0);
            return result;
        }
    }
    async getAllUserData(): Promise<AllUserData> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserData();
                return from_candid_AllUserData_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserData();
            return from_candid_AllUserData_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsersData(): Promise<Array<AllUserData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsersData();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsersData();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocuments(arg0: bigint): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocuments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocuments(arg0);
            return result;
        }
    }
    async getMaterialsByIds(arg0: Array<bigint>): Promise<Array<Material>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaterialsByIds(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaterialsByIds(arg0);
            return result;
        }
    }
    async getMyProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProjects();
            return result;
        }
    }
    async getProductLibrary(): Promise<Array<ProductLibrary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductLibrary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductLibrary();
            return result;
        }
    }
    async getProject(arg0: bigint): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShoppingLists(): Promise<Array<ShoppingList>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShoppingLists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShoppingLists();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async shareProjectWithClient(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.shareProjectWithClient(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.shareProjectWithClient(arg0, arg1);
            return result;
        }
    }
    async updateDocument(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: bigint, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDocument(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDocument(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateUser(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, arg1, arg2, arg3, arg4, to_candid_Role_n16(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, arg1, arg2, arg3, arg4, to_candid_Role_n16(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
}
function from_candid_AllUserData_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AllUserData): AllUserData {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tasks: Array<_Task>;
    projects: Array<_Project>;
    productLibrary: Array<_ProductLibrary>;
    userProfile: _UserProfile;
    moodboards: Array<_Moodboard>;
    shoppingLists: Array<_ShoppingList>;
}): {
    tasks: Array<Task>;
    projects: Array<Project>;
    productLibrary: Array<ProductLibrary>;
    userProfile: UserProfile;
    moodboards: Array<Moodboard>;
    shoppingLists: Array<ShoppingList>;
} {
    return {
        tasks: value.tasks,
        projects: value.projects,
        productLibrary: value.productLibrary,
        userProfile: from_candid_UserProfile_n5(_uploadFile, _downloadFile, value.userProfile),
        moodboards: value.moodboards,
        shoppingLists: value.shoppingLists
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    role: _Role;
    email: string;
    company: string;
    phone: string;
}): {
    id: bigint;
    name: string;
    role: Role;
    email: string;
    company: string;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_Role_n7(_uploadFile, _downloadFile, value.role),
        email: value.email,
        company: value.company,
        phone: value.phone
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    client: null;
} | {
    manager: null;
} | {
    admin: null;
} | {
    designer: null;
}): Role {
    return "client" in value ? Role.client : "manager" in value ? Role.manager : "admin" in value ? Role.admin : "designer" in value ? Role.designer : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AllUserData>): Array<AllUserData> {
    return value.map((x)=>from_candid_AllUserData_n3(_uploadFile, _downloadFile, x));
}
function to_candid_Role_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    role: Role;
    email: string;
    company: string;
    phone: string;
}): {
    id: bigint;
    name: string;
    role: _Role;
    email: string;
    company: string;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        role: to_candid_Role_n16(_uploadFile, _downloadFile, value.role),
        email: value.email,
        company: value.company,
        phone: value.phone
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    client: null;
} | {
    manager: null;
} | {
    admin: null;
} | {
    designer: null;
} {
    return value == Role.client ? {
        client: null
    } : value == Role.manager ? {
        manager: null
    } : value == Role.admin ? {
        admin: null
    } : value == Role.designer ? {
        designer: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
